from collections.abc import Iterable
from typing import Literal

RangeLike = "AddressRange | str"
RangesLike = RangeLike | Iterable[RangeLike]
MergeMode = Literal["overwrite", "opaque", "preserve", "transparent"]
SwapMode = Literal["word", "swapword", "dword", "long", "swaplong"]
IntelHexMode = Literal["auto", "linear", "extended_linear", "segment", "extended_segment"]
SRecordType = Literal["auto", "s1", "s2", "s3", "1", "2", "3"]

class AddressRange:
    def __init__(self, start: int, end: int | None = None, *, length: int | None = None) -> None: ...
    @staticmethod
    def from_start_end(start: int, end: int) -> AddressRange: ...
    @staticmethod
    def from_start_length(start: int, length: int) -> AddressRange: ...
    @staticmethod
    def parse(text: str) -> AddressRange: ...
    @property
    def start(self) -> int: ...
    @property
    def end(self) -> int: ...
    @property
    def length(self) -> int: ...
    def contains(self, addr: int) -> bool: ...

class Segment:
    def __init__(self, start: int, data: bytes) -> None: ...
    @property
    def start(self) -> int: ...
    @property
    def end(self) -> int: ...
    @property
    def data(self) -> bytes: ...
    def __len__(self) -> int: ...

class HexFile:
    def __init__(self) -> None: ...
    @staticmethod
    def from_segments(segments: list[Segment]) -> HexFile: ...
    @staticmethod
    def from_binary(data: bytes, base_address: int = 0) -> HexFile: ...
    @staticmethod
    def from_hex_ascii(data: bytes, base_address: int = 0) -> HexFile: ...
    @staticmethod
    def from_intel_hex(data: bytes) -> HexFile: ...
    @staticmethod
    def from_intel_hex_16bit(data: bytes) -> HexFile: ...
    @staticmethod
    def from_srec(data: bytes) -> HexFile: ...
    def segments(self, *, normalized: bool = False) -> list[Segment]: ...
    def normalized(self) -> HexFile: ...
    def copy(self) -> HexFile: ...
    def is_empty(self) -> bool: ...
    @property
    def min_address(self) -> int | None: ...
    @property
    def max_address(self) -> int | None: ...
    @property
    def total_bytes(self) -> int: ...
    @property
    def gap_count(self) -> int: ...
    def append_segment(self, segment: Segment) -> None: ...
    def prepend_segment(self, segment: Segment) -> None: ...
    def write(self, addr: int, data: bytes) -> None: ...
    def read_byte(self, addr: int) -> int | None: ...
    def read(self, addr: int, length: int) -> bytes | None: ...
    def read_sparse(self, addr: int, length: int) -> list[int | None]: ...
    def to_bytes(self, *, fill: int = 0xFF) -> bytes | None: ...
    def to_binary(self, *, fill_gaps: int | None = None) -> bytes: ...
    def to_intel_hex(self, *, bytes_per_line: int = 32, mode: IntelHexMode | None = None) -> bytes: ...
    def to_srec(self, *, bytes_per_line: int = 16, record_type: SRecordType | None = None) -> bytes: ...
    def to_hex_ascii(self, *, line_length: int = 16, separator: str | None = None) -> bytes: ...
    def filter(self, ranges: RangesLike) -> None: ...
    def cut(self, ranges: RangesLike) -> None: ...
    def fill(self, ranges: RangesLike, *, pattern: bytes | None = None, overwrite: bool = False) -> None: ...
    def fill_gaps(self, *, fill: int = 0xFF) -> None: ...
    def merge(self, other: HexFile, *, mode: MergeMode | None = None, offset: int = 0, range: RangeLike | None = None) -> None: ...
    def offset(self, offset: int) -> None: ...
    def align(self, alignment: int, *, fill: int = 0xFF, length: bool = False) -> None: ...
    def split(self, max_size: int) -> None: ...
    def swap(self, mode: SwapMode) -> None: ...
    def dspic_expand(self, range: RangeLike, target: int | None = None) -> None: ...
    def dspic_shrink(self, range: RangeLike, target: int | None = None) -> None: ...
    def dspic_clear_ghost(self, range: RangeLike) -> None: ...
    def remap(self, start: int, end: int, linear: int, size: int, inc: int) -> None: ...
    def map_star12(self) -> None: ...
    def map_star12x(self) -> None: ...
    def map_star08(self) -> None: ...

class Pipeline:
    def __init__(self) -> None: ...
    def __len__(self) -> int: ...
    def clear(self) -> None: ...
    def apply(self, source: HexFile) -> HexFile: ...
    def fill(self, ranges: RangesLike, *, pattern: bytes | None = None, overwrite: bool = False) -> None: ...
    def cut(self, ranges: RangesLike) -> None: ...
    def filter(self, ranges: RangesLike) -> None: ...
    def merge(self, other: HexFile, *, mode: MergeMode | None = None, offset: int = 0, range: RangeLike | None = None) -> None: ...
    def fill_gaps(self, *, fill: int = 0xFF) -> None: ...
    def align(self, alignment: int, *, fill: int = 0xFF, length: bool = False) -> None: ...
    def split(self, max_size: int) -> None: ...
    def swap(self, mode: SwapMode) -> None: ...
    def map_star12(self) -> None: ...
    def map_star12x(self) -> None: ...
    def map_star08(self) -> None: ...
    def remap(self, start: int, end: int, linear: int, size: int, inc: int) -> None: ...
    def dspic_expand(self, range: RangeLike, target: int | None = None) -> None: ...
    def dspic_shrink(self, range: RangeLike, target: int | None = None) -> None: ...
    def dspic_clear_ghost(self, range: RangeLike) -> None: ...
